/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Swisstronik } from "./Swisstronik";
export * as factories from "./factories";
export { Swisstronik__factory } from "./factories/Swisstronik__factory";
